import type { CountryCardData } from "@expat-atlas/types";

export const SEED_COUNTRIES: CountryCardData[] = [
  {
    slug: "philippines",
    name: "Philippines",
    flagEmoji: "🇵🇭",
    monthlyCostEstimate: "$1,200–$1,800",
    visaComplexity: "Moderate",
    natureScore: 88,
    socialScore: 82,
    healthcareScore: 65,
    internetScore: 70,
    propertyComplexity: "Moderate",
    longStayPotential: "Strong",
    demoData: true,
  },
  {
    slug: "thailand",
    name: "Thailand",
    flagEmoji: "🇹🇭",
    monthlyCostEstimate: "$1,400–$2,200",
    visaComplexity: "Moderate",
    natureScore: 85,
    socialScore: 78,
    healthcareScore: 72,
    internetScore: 85,
    propertyComplexity: "Moderate",
    longStayPotential: "Strong",
    demoData: true,
  },
  {
    slug: "mexico",
    name: "Mexico",
    flagEmoji: "🇲🇽",
    monthlyCostEstimate: "$1,500–$2,500",
    visaComplexity: "Moderate",
    natureScore: 80,
    socialScore: 85,
    healthcareScore: 68,
    internetScore: 78,
    propertyComplexity: "Moderate",
    longStayPotential: "Strong",
    demoData: true,
  },
  {
    slug: "colombia",
    name: "Colombia",
    flagEmoji: "🇨🇴",
    monthlyCostEstimate: "$1,200–$2,000",
    visaComplexity: "Moderate",
    natureScore: 86,
    socialScore: 80,
    healthcareScore: 62,
    internetScore: 75,
    propertyComplexity: "Moderate",
    longStayPotential: "Good",
    demoData: true,
  },
  {
    slug: "portugal",
    name: "Portugal",
    flagEmoji: "🇵🇹",
    monthlyCostEstimate: "$2,200–$3,500",
    visaComplexity: "Higher",
    natureScore: 78,
    socialScore: 75,
    healthcareScore: 85,
    internetScore: 88,
    propertyComplexity: "Higher",
    longStayPotential: "Strong",
    demoData: true,
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    flagEmoji: "🇻🇳",
    monthlyCostEstimate: "$1,000–$1,600",
    visaComplexity: "Moderate",
    natureScore: 82,
    socialScore: 76,
    healthcareScore: 60,
    internetScore: 72,
    propertyComplexity: "Higher",
    longStayPotential: "Good",
    demoData: true,
  },
  {
    slug: "costa-rica",
    name: "Costa Rica",
    flagEmoji: "🇨🇷",
    monthlyCostEstimate: "$2,000–$3,000",
    visaComplexity: "Moderate",
    natureScore: 92,
    socialScore: 74,
    healthcareScore: 70,
    internetScore: 68,
    propertyComplexity: "Moderate",
    longStayPotential: "Good",
    demoData: true,
  },
  {
    slug: "panama",
    name: "Panama",
    flagEmoji: "🇵🇦",
    monthlyCostEstimate: "$1,800–$2,800",
    visaComplexity: "Moderate",
    natureScore: 84,
    socialScore: 72,
    healthcareScore: 68,
    internetScore: 80,
    propertyComplexity: "Moderate",
    longStayPotential: "Good",
    demoData: true,
  },
  {
    slug: "indonesia",
    name: "Indonesia",
    flagEmoji: "🇮🇩",
    monthlyCostEstimate: "$1,100–$1,900",
    visaComplexity: "Moderate",
    natureScore: 90,
    socialScore: 77,
    healthcareScore: 58,
    internetScore: 65,
    propertyComplexity: "Higher",
    longStayPotential: "Good",
    demoData: true,
  },
];
