import type { VisaCardData } from "@expat-atlas/types";

export const SEED_VISAS: VisaCardData[] = [
  {
    id: "ph-tourist",
    countrySlug: "philippines",
    countryName: "Philippines",
    flagEmoji: "🇵🇭",
    name: "Tourist entry (research)",
    category: "Tourist entry",
    overview:
      "May allow short stays for tourism. Extension rules and entry requirements vary — verify with official immigration sources before travel.",
    typicalStay: "Planning estimate: up to 30 days initial entry (verify)",
    estimatedFees: "Varies by nationality — verify official fee schedule",
    riskLevel: "medium",
    reviewStatus: "needs_review",
    confidenceLevel: "low",
    sourceName: "Philippines immigration (verify)",
  },
  {
    id: "th-tourist",
    countrySlug: "thailand",
    countryName: "Thailand",
    flagEmoji: "🇹🇭",
    name: "Tourist visa / visa exemption (research)",
    category: "Tourist entry",
    overview:
      "Common path for first visits and long-stay research trips. Rules differ by passport — this may be worth researching for your citizenship.",
    typicalStay: "Planning estimate: 30–60 days depending on entry type",
    estimatedFees: "Varies — verify embassy guidance",
    riskLevel: "medium",
    reviewStatus: "needs_review",
    confidenceLevel: "low",
    sourceName: "Thai immigration (verify)",
  },
  {
    id: "mx-tourist",
    countrySlug: "mexico",
    countryName: "Mexico",
    flagEmoji: "🇲🇽",
    name: "Visitor permit (FMM) research",
    category: "Tourist entry",
    overview:
      "Often used for land border entries and initial stays. Duration and conditions depend on entry point and officer discretion — verify officially.",
    typicalStay: "Planning estimate: up to 180 days (not guaranteed)",
    estimatedFees: "Often included in travel — verify current rules",
    riskLevel: "medium",
    reviewStatus: "needs_review",
    confidenceLevel: "low",
    sourceName: "INM Mexico (verify)",
  },
  {
    id: "pt-d7",
    countrySlug: "portugal",
    countryName: "Portugal",
    flagEmoji: "🇵🇹",
    name: "D7 / passive income pathway (research)",
    category: "Retirement / passive income",
    overview:
      "May suit remote workers or those with passive income. Requires financial proof and official application — consult licensed professionals.",
    typicalStay: "Residency pathway — not a short tourist stay",
    estimatedFees: "Application + legal fees — verify",
    riskLevel: "high",
    reviewStatus: "needs_review",
    confidenceLevel: "low",
    sourceName: "AIMA Portugal (verify)",
  },
  {
    id: "co-tourist",
    countrySlug: "colombia",
    countryName: "Colombia",
    flagEmoji: "🇨🇴",
    name: "Permiso de ingreso (research)",
    category: "Tourist entry",
    overview:
      "Common for initial exploration stays. Extension and tax implications may apply for longer stays — verify with official sources.",
    typicalStay: "Planning estimate: 90 days initial (verify extensions)",
    estimatedFees: "Varies — verify",
    riskLevel: "medium",
    reviewStatus: "needs_review",
    confidenceLevel: "low",
  },
  {
    id: "vn-tourist",
    countrySlug: "vietnam",
    countryName: "Vietnam",
    flagEmoji: "🇻🇳",
    name: "E-visa / tourist entry (research)",
    category: "Tourist entry",
    overview:
      "E-visa availability depends on nationality. This may be worth researching alongside extension options for longer stays.",
    typicalStay: "Planning estimate: 30–90 days depending on visa type",
    estimatedFees: "E-visa fees vary — verify official portal",
    riskLevel: "medium",
    reviewStatus: "needs_review",
    confidenceLevel: "low",
  },
];
